[package]
name = "neural-amp-modeler-core-bindgen"
version = "0.1.0"
edition = "2024"

[lib]
name = "neural_amp_modeler"
path = "src/lib.rs"

[dependencies]

[build-dependencies]
bindgen = "0.71.1"
dunce = "1.0.5"
cc = "1.2.20"